#!/usr/bin/env bash

while true; do
    CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
    STATUS=$(cat /sys/class/power_supply/BAT0/status)
    if [ $CHARGE -le 20 ] && [ $STATUS == "Discharging" ]; then
        notify-send "Battery Warning" "Battery is at $CHARGE%" -i battery-caution --expire-time 0 -u critical
    fi
    if [ $CHARGE -le 10 ]; then
	    sleep 2m
    else
        sleep 5m
    fi
done
