#!/usr/bin/env bash

base_image_folder="/home/infernox/wallpapers/"

next_image () {
    favourite_next=$(shuf -i 0-4 -n 1)
    if [ $favourite_next -eq 0 ]; then
        image_folder="${base_image_folder}favourites/"
    else
        image_folder=$base_image_folder
    fi
    if [ $favourite_next -eq 1 ]; then
        next_image_file=${base_image_folder}favourites/Quote.png
    elif [ $favourite_next -eq 2 ]; then
        next_image_file=${base_image_folder}favourites/NATO.png
    else
        next_image_file=$(find $image_folder -type f | sort -R | tail -1)
    fi
    hyprctl hyprpaper preload $next_image_file &> /dev/null
    monitors=$(hyprctl monitors | grep Monitor | awk '{print $2}')
    for monitor in $monitors; do
        hyprctl hyprpaper wallpaper "${monitor},${next_image_file}" &> /dev/null
    done
    sleep 0.1
    hyprctl hyprpaper unload all &> /dev/null
}

next_image
