#!/usr/bin/bash

base_image_folder="/home/infernox/wallpapers/"

next_image () {
	favourite_next=$(shuf -i 0-3 -n 1)
	if [ $favourite_next -eq 0 ]; then
		image_folder="${base_image_folder}favourites/"
	else
		image_folder=$base_image_folder
	fi
	next_image_file=$(find $image_folder -type f | sort -R | tail -1)
	hyprctl hyprpaper preload $next_image_file &> /dev/null
	hyprctl hyprpaper wallpaper "eDP-1,${next_image_file}" &> /dev/null
	hyprctl hyprpaper unload all &> /dev/null
	}

next_image
