#!/usr/bin/env bash
NAME=$(basename $0)
PID=$$
PIDFILE=/tmp/$NAME.pid

trap "rm -f $PIDFILE" EXIT

if pidof -o %PPID -x $NAME >/dev/null; then
    echo $PID > $PIDFILE
    sleep 5s
    exit 0
fi

notify-send "Shutdown" "Press shutdown again to confirm" -i application-exit --expire-time 5000 -u critical

while [ $SECONDS -lt 5 ]; do
    if [ -f "$PIDFILE" ]; then
        OTHERPID=`cat $PIDFILE`
        kill $OTHERPID
        systemctl poweroff
        exit 0
    fi
done
exit 0
